# =============================================================================
# Docker Compose file for testing on Go versions 1.14~1.17 and latest.
# =============================================================================
# It is recommended to run specifying a specific Go version and not at once.
#
# Since the service `tidy` will update/re-write the "go.mod" file to the latest
# version, during it's process the "go.mod" file will be gone temporarily. Thus,
# it will cause failure in the other container becaue of missing "go.mod" file.
#
# Recommended usage:
#   docker-compose --file ./.github/docker-compose.yml run tidy && \
#   docker-compose --file ./.github/docker-compose.yml run v1_17
#
# NOT recommended to run all tests at once whith "up":
#   docker-compose --file ./.github/docker-compose.yml up
version: "3.9"
services:
  # Service tidy updates the go.mod to the latest on Go 1.17.
  tidy:
    build:
      context: ..
      dockerfile: ./.github/Dockerfile
      args:
        VARIANT: 1.17-alpine
    volumes:
      - ..:/workspaces
    entrypoint: [ "./.github/go-mod-tidy.sh" ]
  # Service v1_17 runs the tests on latest Go v1.17
  # Note that Go v1.14-16 are not supported.
  v1_17:
    build:
      context: ..
      dockerfile: ./.github/Dockerfile
      args:
        VARIANT: 1.17-alpine
    volumes:
      - ..:/workspaces
  # Service v1_18 runs the tests on latest Go v1.18
  v1_18:
    build:
      context: ..
      dockerfile: ./.github/Dockerfile
      args:
        VARIANT: 1.18-alpine
    volumes:
      - ..:/workspaces
  # Service latest runs the tests on latest Go
  latest:
    build:
      context: ..
      dockerfile: ./.github/Dockerfile
      args:
        VARIANT: alpine
    volumes:
      - ..:/workspaces
